// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package task

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskChecklistFieldNames          = builder.RawFieldNames(&TaskChecklist{})
	taskChecklistRows                = strings.Join(taskChecklistFieldNames, ",")
	taskChecklistRowsExpectAutoSet   = strings.Join(stringx.Remove(taskChecklistFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taskChecklistRowsWithPlaceHolder = strings.Join(stringx.Remove(taskChecklistFieldNames, "`checklist_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	taskChecklistModel interface {
		Insert(ctx context.Context, data *TaskChecklist) (sql.Result, error)
		FindOne(ctx context.Context, checklistId string) (*TaskChecklist, error)
		Update(ctx context.Context, data *TaskChecklist) error
		Delete(ctx context.Context, checklistId string) error
	}

	defaultTaskChecklistModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaskChecklist struct {
		ChecklistId  string       `db:"checklist_id"`  // 清单ID
		TaskNodeId   string       `db:"task_node_id"`  // 关联的任务节点ID
		CreatorId    string       `db:"creator_id"`    // 创建该清单的员工ID
		Content      string       `db:"content"`       // 清单内容
		IsCompleted  int64        `db:"is_completed"`  // 是否已完成：0-未完成，1-已完成
		CompleteTime sql.NullTime `db:"complete_time"` // 完成时间
		SortOrder    int64        `db:"sort_order"`    // 排序顺序
		CreateTime   time.Time    `db:"create_time"`   // 创建时间
		UpdateTime   time.Time    `db:"update_time"`   // 更新时间
		DeleteTime   sql.NullTime `db:"delete_time"`   // 删除时间
	}
)

func newTaskChecklistModel(conn sqlx.SqlConn) *defaultTaskChecklistModel {
	return &defaultTaskChecklistModel{
		conn:  conn,
		table: "`task_checklist`",
	}
}

func (m *defaultTaskChecklistModel) Delete(ctx context.Context, checklistId string) error {
	query := fmt.Sprintf("delete from %s where `checklist_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, checklistId)
	return err
}

func (m *defaultTaskChecklistModel) FindOne(ctx context.Context, checklistId string) (*TaskChecklist, error) {
	query := fmt.Sprintf("select %s from %s where `checklist_id` = ? limit 1", taskChecklistRows, m.table)
	var resp TaskChecklist
	err := m.conn.QueryRowCtx(ctx, &resp, query, checklistId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskChecklistModel) Insert(ctx context.Context, data *TaskChecklist) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, taskChecklistRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChecklistId, data.TaskNodeId, data.CreatorId, data.Content, data.IsCompleted, data.CompleteTime, data.SortOrder, data.DeleteTime)
	return ret, err
}

func (m *defaultTaskChecklistModel) Update(ctx context.Context, data *TaskChecklist) error {
	query := fmt.Sprintf("update %s set %s where `checklist_id` = ?", m.table, taskChecklistRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TaskNodeId, data.CreatorId, data.Content, data.IsCompleted, data.CompleteTime, data.SortOrder, data.DeleteTime, data.ChecklistId)
	return err
}

func (m *defaultTaskChecklistModel) tableName() string {
	return m.table
}
