// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package task

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Task_comment 任务评论结构体
type Task_comment struct {
	ID              bson.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	CommentID       string        `bson:"commentId" json:"commentId"`             // 评论ID
	TaskID          string        `bson:"taskId" json:"taskId"`                   // 任务ID
	TaskNodeID      string        `bson:"taskNodeId" json:"taskNodeId"`           // 任务节点ID
	UserID          string        `bson:"userId" json:"userId"`                   // 用户ID
	UserName        string        `bson:"userName" json:"userName"`               // 用户名
	EmployeeID      string        `bson:"employeeId" json:"employeeId"`           // 员工ID
	EmployeeName    string        `bson:"employeeName" json:"employeeName"`       // 员工姓名
	Avatar          string        `bson:"avatar" json:"avatar"`                   // 用户头像
	Content         string        `bson:"content" json:"content"`                 // 评论内容
	ContentHTML     string        `bson:"contentHtml" json:"contentHtml"`         // HTML格式内容
	AtEmployeeIDs   []string      `bson:"atEmployeeIds" json:"atEmployeeIds"`     // @的员工ID列表
	AtEmployeeNames []string      `bson:"atEmployeeNames" json:"atEmployeeNames"` // @的员工姓名列表
	ParentID        string        `bson:"parentId" json:"parentId"`               // 父评论ID（用于回复）
	ReplyToUserID   string        `bson:"replyToUserId" json:"replyToUserId"`     // 回复目标用户ID
	ReplyToName     string        `bson:"replyToName" json:"replyToName"`         // 回复目标用户名
	AttachmentIDs   []string      `bson:"attachmentIds" json:"attachmentIds"`     // 附件ID列表
	AttachmentURLs  []string      `bson:"attachmentUrls" json:"attachmentUrls"`   // 附件URL列表
	LikeCount       int64         `bson:"likeCount" json:"likeCount"`             // 点赞数
	LikedBy         []string      `bson:"likedBy" json:"likedBy"`                 // 点赞用户ID列表
	IsDeleted       bool          `bson:"isDeleted" json:"isDeleted"`             // 是否已删除
	DeletedAt       time.Time     `bson:"deletedAt" json:"deletedAt"`             // 删除时间
	CreateAt        time.Time     `bson:"createAt" json:"createAt"`               // 创建时间
	UpdateAt        time.Time     `bson:"updateAt" json:"updateAt"`               // 更新时间
}

type task_commentModel interface {
	Insert(ctx context.Context, data *Task_comment) error
	FindOne(ctx context.Context, id string) (*Task_comment, error)
	FindByCommentID(ctx context.Context, commentID string) (*Task_comment, error)
	FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindByUserID(ctx context.Context, userID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindReplies(ctx context.Context, parentID string) ([]*Task_comment, error)
	Update(ctx context.Context, data *Task_comment) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	SoftDelete(ctx context.Context, id string) error
	AddLike(ctx context.Context, commentID, userID string) error
	RemoveLike(ctx context.Context, commentID, userID string) error
}

type defaultTask_commentModel struct {
	conn *mon.Model
}

func newDefaultTask_commentModel(conn *mon.Model) *defaultTask_commentModel {
	return &defaultTask_commentModel{conn: conn}
}

func (m *defaultTask_commentModel) Insert(ctx context.Context, data *Task_comment) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultTask_commentModel) FindOne(ctx context.Context, id string) (*Task_comment, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Task_comment
	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTask_commentModel) FindByCommentID(ctx context.Context, commentID string) (*Task_comment, error) {
	var data Task_comment
	err := m.conn.FindOne(ctx, &data, bson.M{"commentId": commentID, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTask_commentModel) FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"taskId": taskID, "isDeleted": bson.M{"$ne": true}}

	// 计算总数
	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	// 分页查询
	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"taskNodeId": taskNodeID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindByUserID(ctx context.Context, userID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"userId": userID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindReplies(ctx context.Context, parentID string) ([]*Task_comment, error) {
	filter := bson.M{"parentId": parentID, "isDeleted": bson.M{"$ne": true}}
	opts := options.Find().SetSort(bson.M{"createAt": 1})

	var data []*Task_comment
	err := m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func (m *defaultTask_commentModel) Update(ctx context.Context, data *Task_comment) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultTask_commentModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}

func (m *defaultTask_commentModel) SoftDelete(ctx context.Context, id string) error {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.UpdateOne(ctx, bson.M{"_id": oid}, bson.M{
		"$set": bson.M{
			"isDeleted": true,
			"deletedAt": time.Now(),
			"updateAt":  time.Now(),
		},
	})
	return err
}

func (m *defaultTask_commentModel) AddLike(ctx context.Context, commentID, userID string) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"commentId": commentID}, bson.M{
		"$addToSet": bson.M{"likedBy": userID},
		"$inc":      bson.M{"likeCount": 1},
		"$set":      bson.M{"updateAt": time.Now()},
	})
	return err
}

func (m *defaultTask_commentModel) RemoveLike(ctx context.Context, commentID, userID string) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"commentId": commentID}, bson.M{
		"$pull": bson.M{"likedBy": userID},
		"$inc":  bson.M{"likeCount": -1},
		"$set":  bson.M{"updateAt": time.Now()},
	})
	return err
}
