// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package task

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

type task_project_detailModel interface {
	Insert(ctx context.Context, data *Task_project_detail) error
	FindOne(ctx context.Context, id string) (*Task_project_detail, error)
	Update(ctx context.Context, data *Task_project_detail) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultTask_project_detailModel struct {
	conn *mon.Model
}

func newDefaultTask_project_detailModel(conn *mon.Model) *defaultTask_project_detailModel {
	return &defaultTask_project_detailModel{conn: conn}
}

func (m *defaultTask_project_detailModel) Insert(ctx context.Context, data *Task_project_detail) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultTask_project_detailModel) FindOne(ctx context.Context, id string) (*Task_project_detail, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Task_project_detail

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotMongoFound
	default:
		return nil, err
	}
}

func (m *defaultTask_project_detailModel) Update(ctx context.Context, data *Task_project_detail) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultTask_project_detailModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
