// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package task

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type task_commentModel interface {
	Insert(ctx context.Context, data *Task_comment) error
	FindOne(ctx context.Context, id string) (*Task_comment, error)
	FindByCommentID(ctx context.Context, commentID string) (*Task_comment, error)
	FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindByUserID(ctx context.Context, userID string, page, pageSize int64) ([]*Task_comment, int64, error)
	FindReplies(ctx context.Context, parentID string) ([]*Task_comment, error)
	Update(ctx context.Context, data *Task_comment) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	SoftDelete(ctx context.Context, id string) error
	AddLike(ctx context.Context, commentID, userID string) error
	RemoveLike(ctx context.Context, commentID, userID string) error
}

type defaultTask_commentModel struct {
	conn *mon.Model
}

func newDefaultTask_commentModel(conn *mon.Model) *defaultTask_commentModel {
	return &defaultTask_commentModel{conn: conn}
}

func (m *defaultTask_commentModel) Insert(ctx context.Context, data *Task_comment) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultTask_commentModel) FindOne(ctx context.Context, id string) (*Task_comment, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Task_comment
	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTask_commentModel) FindByCommentID(ctx context.Context, commentID string) (*Task_comment, error) {
	var data Task_comment
	err := m.conn.FindOne(ctx, &data, bson.M{"commentId": commentID, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTask_commentModel) FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"taskId": taskID, "isDeleted": bson.M{"$ne": true}}

	// 计算总数
	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	// 分页查询
	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"taskNodeId": taskNodeID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindByUserID(ctx context.Context, userID string, page, pageSize int64) ([]*Task_comment, int64, error) {
	filter := bson.M{"userId": userID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Task_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultTask_commentModel) FindReplies(ctx context.Context, parentID string) ([]*Task_comment, error) {
	filter := bson.M{"parentId": parentID, "isDeleted": bson.M{"$ne": true}}
	opts := options.Find().SetSort(bson.M{"createAt": 1})

	var data []*Task_comment
	err := m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func (m *defaultTask_commentModel) Update(ctx context.Context, data *Task_comment) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultTask_commentModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}

func (m *defaultTask_commentModel) SoftDelete(ctx context.Context, id string) error {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.UpdateOne(ctx, bson.M{"_id": oid}, bson.M{
		"$set": bson.M{
			"isDeleted": true,
			"deletedAt": time.Now(),
			"updateAt":  time.Now(),
		},
	})
	return err
}

func (m *defaultTask_commentModel) AddLike(ctx context.Context, commentID, userID string) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"commentId": commentID}, bson.M{
		"$addToSet": bson.M{"likedBy": userID},
		"$inc":      bson.M{"likeCount": 1},
		"$set":      bson.M{"updateAt": time.Now()},
	})
	return err
}

func (m *defaultTask_commentModel) RemoveLike(ctx context.Context, commentID, userID string) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"commentId": commentID}, bson.M{
		"$pull": bson.M{"likedBy": userID},
		"$inc":  bson.M{"likeCount": -1},
		"$set":  bson.M{"updateAt": time.Now()},
	})
	return err
}
