// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ai "task_Project/task/internal/handler/ai"
	auth "task_Project/task/internal/handler/auth"
	checklist "task_Project/task/internal/handler/checklist"
	company "task_Project/task/internal/handler/company"
	dashboard "task_Project/task/internal/handler/dashboard"
	department "task_Project/task/internal/handler/department"
	employee "task_Project/task/internal/handler/employee"
	handover "task_Project/task/internal/handler/handover"
	notification "task_Project/task/internal/handler/notification"
	position "task_Project/task/internal/handler/position"
	role "task_Project/task/internal/handler/role"
	task "task_Project/task/internal/handler/task"
	tasknode "task_Project/task/internal/handler/tasknode"
	upload "task_Project/task/internal/handler/upload"
	user "task_Project/task/internal/handler/user"
	"task_Project/task/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 用户登出
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				// 重置密码
				Method:  http.MethodPost,
				Path:    "/reset-password",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				// 发送验证码
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: auth.SendVerificationCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 审批任务节点完成
				Method:  http.MethodPost,
				Path:    "/approve/completion",
				Handler: checklist.ApproveTaskNodeCompletionHandler(serverCtx),
			},
			{
				// 批量完成/取消完成清单
				Method:  http.MethodPost,
				Path:    "/batch/complete",
				Handler: checklist.BatchCompleteChecklistHandler(serverCtx),
			},
			{
				// 创建任务清单
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: checklist.CreateChecklistHandler(serverCtx),
			},
			{
				// 删除任务清单
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: checklist.DeleteChecklistHandler(serverCtx),
			},
			{
				// 获取任务清单信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: checklist.GetChecklistHandler(serverCtx),
			},
			{
				// 获取任务节点下的所有清单
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: checklist.GetChecklistListHandler(serverCtx),
			},
			{
				// 获取我的清单列表
				Method:  http.MethodPost,
				Path:    "/my",
				Handler: checklist.GetMyChecklistHandler(serverCtx),
			},
			{
				// 提交任务节点完成审批
				Method:  http.MethodPost,
				Path:    "/submit/approval",
				Handler: checklist.SubmitTaskNodeCompletionApprovalHandler(serverCtx),
			},
			{
				// 更新任务清单
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: checklist.UpdateChecklistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/checklist"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建公司
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: company.CreateCompanyHandler(serverCtx),
			},
			{
				// 删除公司
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: company.DeleteCompanyHandler(serverCtx),
			},
			{
				// 获取公司信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: company.GetCompanyHandler(serverCtx),
			},
			{
				// 获取公司列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: company.GetCompanyListHandler(serverCtx),
			},
			{
				// 生成邀请码
				Method:  http.MethodPost,
				Path:    "/invite/generate",
				Handler: company.GenerateInviteCodeHandler(serverCtx),
			},
			{
				// 解析邀请码
				Method:  http.MethodPost,
				Path:    "/invite/parse",
				Handler: company.ParseInviteCodeHandler(serverCtx),
			},
			{
				// 更新公司信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: company.UpdateCompanyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/company"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建部门
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: department.CreateDepartmentHandler(serverCtx),
			},
			{
				// 删除部门
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: department.DeleteDepartmentHandler(serverCtx),
			},
			{
				// 获取部门信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: department.GetDepartmentHandler(serverCtx),
			},
			{
				// 获取部门列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: department.GetDepartmentListHandler(serverCtx),
			},
			{
				// 更新部门信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: department.UpdateDepartmentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/department"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建员工
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: employee.CreateEmployeeHandler(serverCtx),
			},
			{
				// 删除员工
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: employee.DeleteEmployeeHandler(serverCtx),
			},
			{
				// 获取员工信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: employee.GetEmployeeHandler(serverCtx),
			},
			{
				// 加入公司
				Method:  http.MethodPost,
				Path:    "/join",
				Handler: employee.JoinCompanyHandler(serverCtx),
			},
			{
				// 申请加入公司
				Method:  http.MethodPost,
				Path:    "/join/apply",
				Handler: employee.ApplyJoinCompanyHandler(serverCtx),
			},
			{
				// 审批加入公司申请
				Method:  http.MethodPost,
				Path:    "/join/approve",
				Handler: employee.ApproveJoinApplicationHandler(serverCtx),
			},
			{
				// 获取待审批加入申请列表
				Method:  http.MethodPost,
				Path:    "/join/pending",
				Handler: employee.GetPendingJoinApplicationsHandler(serverCtx),
			},
			{
				// 员工离职
				Method:  http.MethodPost,
				Path:    "/leave",
				Handler: employee.EmployeeLeaveHandler(serverCtx),
			},
			{
				// 确认离职审批
				Method:  http.MethodPost,
				Path:    "/leave/approve",
				Handler: employee.ConfirmLeaveApprovalHandler(serverCtx),
			},
			{
				// 获取员工列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: employee.GetEmployeeListHandler(serverCtx),
			},
			{
				// 获取当前登录员工信息
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: employee.GetSelfEmployeeHandler(serverCtx),
			},
			{
				// 更新员工信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: employee.UpdateEmployeeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/employee"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 审批任务交接
				Method:  http.MethodPost,
				Path:    "/approve",
				Handler: handover.ApproveHandoverHandler(serverCtx),
			},
			{
				// 确认交接
				Method:  http.MethodPost,
				Path:    "/confirm",
				Handler: handover.ConfirmHandoverHandler(serverCtx),
			},
			{
				// 创建任务交接
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: handover.CreateHandoverHandler(serverCtx),
			},
			{
				// 获取交接信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: handover.GetHandoverHandler(serverCtx),
			},
			{
				// 获取交接列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: handover.GetHandoverListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/handover"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建通知
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: notification.CreateNotificationHandler(serverCtx),
			},
			{
				// 获取通知信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: notification.GetNotificationHandler(serverCtx),
			},
			{
				// 获取通知列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: notification.GetNotificationListHandler(serverCtx),
			},
			{
				// 标记通知为已读
				Method:  http.MethodPut,
				Path:    "/read",
				Handler: notification.MarkNotificationReadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/notification"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建职位
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: position.CreatePositionHandler(serverCtx),
			},
			{
				// 删除职位
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: position.DeletePositionHandler(serverCtx),
			},
			{
				// 获取职位信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: position.GetPositionHandler(serverCtx),
			},
			{
				// 获取职位列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: position.GetPositionListHandler(serverCtx),
			},
			{
				// 更新职位信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: position.UpdatePositionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/position"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 员工赋予角色
				Method:  http.MethodPost,
				Path:    "/assign",
				Handler: role.AssignRoleHandler(serverCtx),
			},
			{
				// 创建角色
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: role.CreateRoleHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
			{
				// 查询员工的角色列表
				Method:  http.MethodPost,
				Path:    "/employeeRoles",
				Handler: role.EmployeeRolesHandler(serverCtx),
			},
			{
				// 角色列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: role.RoleListHandler(serverCtx),
			},
			{
				// 查询职位的角色列表
				Method:  http.MethodPost,
				Path:    "/positionRoles",
				Handler: role.PositionRolesHandler(serverCtx),
			},
			{
				// 员工撤销角色
				Method:  http.MethodPost,
				Path:    "/revoke",
				Handler: role.RevokeRoleHandler(serverCtx),
			},
			{
				// 更新角色
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: role.UpdateRoleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/role"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建任务评论
				Method:  http.MethodPost,
				Path:    "/comment/create",
				Handler: task.CreateTaskCommentHandler(serverCtx),
			},
			{
				// 删除任务评论
				Method:  http.MethodPost,
				Path:    "/comment/delete",
				Handler: task.DeleteTaskCommentHandler(serverCtx),
			},
			{
				// 点赞/取消点赞任务评论
				Method:  http.MethodPost,
				Path:    "/comment/like",
				Handler: task.LikeTaskCommentHandler(serverCtx),
			},
			{
				// 获取任务评论列表
				Method:  http.MethodPost,
				Path:    "/comment/list",
				Handler: task.GetTaskCommentsHandler(serverCtx),
			},
			{
				// 任务完成
				Method:  http.MethodPost,
				Path:    "/complete",
				Handler: task.CompleteTaskHandler(serverCtx),
			},
			{
				// 创建任务
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: task.CreateTaskHandler(serverCtx),
			},
			{
				// 删除任务
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: task.DeleteTaskHandler(serverCtx),
			},
			{
				// 更新任务详情（添加文件）
				Method:  http.MethodPut,
				Path:    "/detail",
				Handler: task.UpdateTaskDetailHandler(serverCtx),
			},
			{
				// 任务自动派发
				Method:  http.MethodPost,
				Path:    "/dispatch",
				Handler: task.AutoDispatchHandler(serverCtx),
			},
			{
				// 获取任务信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: task.GetTaskHandler(serverCtx),
			},
			{
				// 获取任务列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: task.GetTaskListHandler(serverCtx),
			},
			{
				// 任务进度更新
				Method:  http.MethodPut,
				Path:    "/progress",
				Handler: task.UpdateTaskProgressHandler(serverCtx),
			},
			{
				// 更新任务信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: task.UpdateTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建任务节点
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: tasknode.CreateTaskNodeHandler(serverCtx),
			},
			{
				// 删除任务节点
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: tasknode.DeleteTaskNodeHandler(serverCtx),
			},
			{
				// 获取任务节点信息
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: tasknode.GetTaskNodeHandler(serverCtx),
			},
			{
				// 获取用户的任务节点信息
				Method:  http.MethodGet,
				Path:    "/get/user",
				Handler: tasknode.GetUserTaskNodeHandler(serverCtx),
			},
			{
				// 获取任务节点列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: tasknode.GetTaskNodeListHandler(serverCtx),
			},
			{
				// 更新任务节点
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: tasknode.UpdateTaskNodeHandler(serverCtx),
			},
			{
				// 更新前置节点（专门用于更新前置节点关系）
				Method:  http.MethodPut,
				Path:    "/update/prerequisites",
				Handler: tasknode.UpdatePrerequisiteNodesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/tasknode"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 上传头像
				Method:  http.MethodPost,
				Path:    "/avatar",
				Handler: upload.UploadAvatarHandler(serverCtx),
			},
			{
				// 创建附件评论
				Method:  http.MethodPost,
				Path:    "/comment/create",
				Handler: upload.CreateAttachmentCommentHandler(serverCtx),
			},
			{
				// 删除附件评论
				Method:  http.MethodPost,
				Path:    "/comment/delete",
				Handler: upload.DeleteAttachmentCommentHandler(serverCtx),
			},
			{
				// 获取附件评论列表
				Method:  http.MethodPost,
				Path:    "/comment/list",
				Handler: upload.GetAttachmentCommentsHandler(serverCtx),
			},
			{
				// 解决附件评论
				Method:  http.MethodPost,
				Path:    "/comment/resolve",
				Handler: upload.ResolveAttachmentCommentHandler(serverCtx),
			},
			{
				// 删除附件
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: upload.DeleteAttachmentHandler(serverCtx),
			},
			{
				// 文件上传（支持图片、PDF、Markdown等文件）
				Method:  http.MethodPost,
				Path:    "/file",
				Handler: upload.UploadInfoHandler(serverCtx),
			},
			{
				// 获取文件详情
				Method:  http.MethodPost,
				Path:    "/file/detail",
				Handler: upload.GetFileDetailHandler(serverCtx),
			},
			{
				// 代理文件内容（解决CORS问题）
				Method:  http.MethodGet,
				Path:    "/file/proxy",
				Handler: upload.ProxyFileHandler(serverCtx),
			},
			{
				// 获取任务附件列表
				Method:  http.MethodPost,
				Path:    "/task/attachments",
				Handler: upload.GetTaskAttachmentsHandler(serverCtx),
			},
			{
				// 获取任务节点附件列表
				Method:  http.MethodPost,
				Path:    "/tasknode/attachments",
				Handler: upload.GetTaskNodeAttachmentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/upload"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 更新用户信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: user.UpdateInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取AI工作建议
				Method:  http.MethodGet,
				Path:    "/suggestion",
				Handler: ai.GetAiSuggestionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取仪表盘统计数据
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: dashboard.GetDashboardStatsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/dashboard"),
	)
}
