// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package upload

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type attachment_commentModel interface {
	Insert(ctx context.Context, data *Attachment_comment) error
	FindOne(ctx context.Context, id string) (*Attachment_comment, error)
	FindByCommentID(ctx context.Context, commentID string) (*Attachment_comment, error)
	FindByFileID(ctx context.Context, fileID string, page, pageSize int64) ([]*Attachment_comment, int64, error)
	FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Attachment_comment, int64, error)
	FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Attachment_comment, int64, error)
	FindReplies(ctx context.Context, parentID string) ([]*Attachment_comment, error)
	Update(ctx context.Context, data *Attachment_comment) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	SoftDelete(ctx context.Context, id string) error
	MarkResolved(ctx context.Context, commentID, resolvedBy string) error
}

type defaultAttachment_commentModel struct {
	conn *mon.Model
}

func newDefaultAttachment_commentModel(conn *mon.Model) *defaultAttachment_commentModel {
	return &defaultAttachment_commentModel{conn: conn}
}

func (m *defaultAttachment_commentModel) Insert(ctx context.Context, data *Attachment_comment) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultAttachment_commentModel) FindOne(ctx context.Context, id string) (*Attachment_comment, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Attachment_comment
	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAttachment_commentModel) FindByCommentID(ctx context.Context, commentID string) (*Attachment_comment, error) {
	var data Attachment_comment
	err := m.conn.FindOne(ctx, &data, bson.M{"commentId": commentID, "isDeleted": bson.M{"$ne": true}})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAttachment_commentModel) FindByFileID(ctx context.Context, fileID string, page, pageSize int64) ([]*Attachment_comment, int64, error) {
	filter := bson.M{"fileId": fileID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Attachment_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultAttachment_commentModel) FindByTaskID(ctx context.Context, taskID string, page, pageSize int64) ([]*Attachment_comment, int64, error) {
	filter := bson.M{"taskId": taskID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Attachment_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultAttachment_commentModel) FindByTaskNodeID(ctx context.Context, taskNodeID string, page, pageSize int64) ([]*Attachment_comment, int64, error) {
	filter := bson.M{"taskNodeId": taskNodeID, "isDeleted": bson.M{"$ne": true}}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Attachment_comment
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultAttachment_commentModel) FindReplies(ctx context.Context, parentID string) ([]*Attachment_comment, error) {
	filter := bson.M{"parentId": parentID, "isDeleted": bson.M{"$ne": true}}
	opts := options.Find().SetSort(bson.M{"createAt": 1})

	var data []*Attachment_comment
	err := m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func (m *defaultAttachment_commentModel) Update(ctx context.Context, data *Attachment_comment) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultAttachment_commentModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}

func (m *defaultAttachment_commentModel) SoftDelete(ctx context.Context, id string) error {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.UpdateOne(ctx, bson.M{"_id": oid}, bson.M{
		"$set": bson.M{
			"isDeleted": true,
			"deletedAt": time.Now(),
			"updateAt":  time.Now(),
		},
	})
	return err
}

func (m *defaultAttachment_commentModel) MarkResolved(ctx context.Context, commentID, resolvedBy string) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"commentId": commentID}, bson.M{
		"$set": bson.M{
			"isResolved": true,
			"resolvedBy": resolvedBy,
			"resolvedAt": time.Now(),
			"updateAt":   time.Now(),
		},
	})
	return err
}
