// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package upload

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

type upload_fileModel interface {
	Insert(ctx context.Context, data *Upload_file) error
	FindOne(ctx context.Context, id string) (*Upload_file, error)
	FindByFileID(ctx context.Context, fileID string) (*Upload_file, error)
	FindByRelatedID(ctx context.Context, relatedID string, page, pageSize int64) ([]*Upload_file, int64, error)
	FindByModule(ctx context.Context, module string, page, pageSize int64) ([]*Upload_file, int64, error)
	FindByModuleAndRelatedID(ctx context.Context, module, relatedID string) ([]*Upload_file, error)
	Update(ctx context.Context, data *Upload_file) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	DeleteByFileID(ctx context.Context, fileID string) (int64, error)
}

type defaultUpload_fileModel struct {
	conn *mon.Model
}

func newDefaultUpload_fileModel(conn *mon.Model) *defaultUpload_fileModel {
	return &defaultUpload_fileModel{conn: conn}
}

func (m *defaultUpload_fileModel) Insert(ctx context.Context, data *Upload_file) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultUpload_fileModel) FindOne(ctx context.Context, id string) (*Upload_file, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Upload_file

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpload_fileModel) FindByFileID(ctx context.Context, fileID string) (*Upload_file, error) {
	var data Upload_file
	err := m.conn.FindOne(ctx, &data, bson.M{"fileId": fileID})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpload_fileModel) FindByRelatedID(ctx context.Context, relatedID string, page, pageSize int64) ([]*Upload_file, int64, error) {
	filter := bson.M{"relatedId": relatedID}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Upload_file
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultUpload_fileModel) FindByModule(ctx context.Context, module string, page, pageSize int64) ([]*Upload_file, int64, error) {
	filter := bson.M{"module": module}

	total, err := m.conn.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}

	skip := (page - 1) * pageSize
	opts := options.Find().SetSort(bson.M{"createAt": -1}).SetSkip(skip).SetLimit(pageSize)

	var data []*Upload_file
	err = m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, 0, err
	}

	return data, total, nil
}

func (m *defaultUpload_fileModel) FindByModuleAndRelatedID(ctx context.Context, module, relatedID string) ([]*Upload_file, error) {
	filter := bson.M{"module": module, "relatedId": relatedID}
	opts := options.Find().SetSort(bson.M{"createAt": -1})

	var data []*Upload_file
	err := m.conn.Find(ctx, &data, filter, opts)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func (m *defaultUpload_fileModel) Update(ctx context.Context, data *Upload_file) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultUpload_fileModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}

func (m *defaultUpload_fileModel) DeleteByFileID(ctx context.Context, fileID string) (int64, error) {
	res, err := m.conn.DeleteOne(ctx, bson.M{"fileId": fileID})
	return res, err
}
