// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApproveHandoverRequest struct {
	HandoverID   string `json:"handoverId"`
	Approved     int    `json:"approved"`
	Comment      string `json:"comment,optional"`
	ToEmployeeID string `json:"toEmployeeId,optional"` // 指定交接人（审批时可选）
}

type AssignRoleRequest struct {
	PositionId string `json:"positionId"` // 职位ID（改为给职位分配角色）
	RoleId     string `json:"roleId"`
	ExpireTime string `json:"expireTime,optional"`
}

type AutoDispatchRequest struct {
	TaskID string `json:"taskId"`
}

type BaseResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"`
}

type CompanyInfo struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	CompanyAttributes int    `json:"companyAttributes"`
	CompanyBusiness   int    `json:"companyBusiness"`
	Owner             string `json:"owner"`
	Description       string `json:"description"`
	Address           string `json:"address"`
	Phone             string `json:"phone"`
	Email             string `json:"email"`
	Status            int    `json:"status"`
	CreateTime        string `json:"createTime"`
	UpdateTime        string `json:"updateTime"`
}

type CompanyListRequest struct {
	PageReq
	Name string `json:"name,optional"`
}

type CompleteTaskRequest struct {
	TaskID         string `json:"taskId"`
	ActualHours    int    `json:"actualHours,optional"`
	CompletionNote string `json:"completionNote,optional"`
}

type ConfirmHandoverRequest struct {
	HandoverID string `json:"handoverId"`
}

type ConfirmLeaveApprovalRequest struct {
	ApprovalID string `json:"approvalId"`
	Approved   bool   `json:"approved"`
	Note       string `json:"note,optional"`
}

type JoinCompanyRequest struct {
	CompanyID    string `json:"companyId"`
	DepartmentID string `json:"departmentId,optional"`
	PositionID   string `json:"positionId,optional"`
}

// 生成邀请码请求
type GenerateInviteCodeRequest struct {
	ExpireDays int `json:"expireDays,optional"` // 过期天数，默认7天
	MaxUses    int `json:"maxUses,optional"`    // 最大使用次数，0表示不限制
}

// 解析邀请码请求
type ParseInviteCodeRequest struct {
	InviteCode string `json:"inviteCode"`
}

// 解析邀请码响应数据
type InviteCodeInfo struct {
	CompanyID   string `json:"companyId"`
	CompanyName string `json:"companyName"`
	ExpireAt    string `json:"expireAt"`
	MaxUses     int    `json:"maxUses"`
	UsedCount   int    `json:"usedCount"`
}

// 申请加入公司请求
type ApplyJoinCompanyRequest struct {
	InviteCode  string `json:"inviteCode"`
	ApplyReason string `json:"applyReason,optional"` // 申请理由
}

// 审批加入申请请求
type ApproveJoinApplicationRequest struct {
	ApplicationID string `json:"applicationId"`
	Approved      bool   `json:"approved"`
	Note          string `json:"note,optional"`         // 审批备注
	DepartmentID  string `json:"departmentId,optional"` // 指定部门
	PositionID    string `json:"positionId,optional"`   // 指定职位
}

// 获取待审批申请列表请求
type GetPendingJoinApplicationsRequest struct {
	PageReq
}

// 加入申请信息
type JoinApplicationInfo struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	Username    string `json:"username"`
	RealName    string `json:"realName"`
	CompanyID   string `json:"companyId"`
	CompanyName string `json:"companyName"`
	InviteCode  string `json:"inviteCode,optional"`
	ApplyReason string `json:"applyReason,optional"`
	Status      int    `json:"status"` // 0-待审批 1-已通过 2-已拒绝 3-已取消
	ApproverID  string `json:"approverId,optional"`
	ApproveTime string `json:"approveTime,optional"`
	ApproveNote string `json:"approveNote,optional"`
	CreateTime  string `json:"createTime"`
}

type CreateCompanyRequest struct {
	Name              string `json:"name"`
	CompanyAttributes int    `json:"companyAttributes"`
	CompanyBusiness   int    `json:"companyBusiness"`
	Description       string `json:"description,optional"`
	Address           string `json:"address,optional"`
	Phone             string `json:"phone,optional"`
	Email             string `json:"email,optional"`
	UseTemplate       bool   `json:"useTemplate,optional"` // 是否使用组织结构模板
}

type CreateDepartmentRequest struct {
	CompanyID      string `json:"companyId"`
	DepartmentName string `json:"departmentName"`
	ParentID       string `json:"parentId,optional"`
	DepartmentCode string `json:"departmentCode"`
	ManagerID      string `json:"managerId,optional"`
	Description    string `json:"description,optional"`
}

type CreateEmployeeRequest struct {
	UserID       string `json:"userId"`
	CompanyID    string `json:"companyId"`
	DepartmentID string `json:"departmentId,optional"`
	PositionID   string `json:"positionId,optional"`
	EmployeeID   string `json:"employeeId"`
	RealName     string `json:"realName"`
	WorkEmail    string `json:"workEmail,optional"`
	WorkPhone    string `json:"workPhone,optional"`
	Skills       string `json:"skills,optional"`
	RoleTags     string `json:"roleTags,optional"`
	HireDate     string `json:"hireDate,optional"`
}

type CreateHandoverRequest struct {
	TaskID         string `json:"taskId"`
	FromEmployeeID string `json:"fromEmployeeId"`
	ToEmployeeID   string `json:"toEmployeeId"`
	HandoverReason string `json:"handoverReason"`
	HandoverNote   string `json:"handoverNote,optional"`
	ApproverID     string `json:"approverId,optional"`
}

type CreateNotificationRequest struct {
	EmployeeID  string `json:"employeeId"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Type        int    `json:"type"`
	Priority    int    `json:"priority,optional"`
	RelatedID   string `json:"relatedId,optional"`
	RelatedType string `json:"relatedType,optional"`
}

type CreatePositionRequest struct {
	DepartmentID     string   `json:"departmentId"`
	PositionName     string   `json:"positionName"`
	PositionCode     string   `json:"positionCode"`
	PositionLevel    int      `json:"positionLevel"`
	RequiredSkills   string   `json:"requiredSkills,optional"`
	JobDescription   string   `json:"jobDescription,optional"`
	Responsibilities string   `json:"responsibilities,optional"`
	Requirements     string   `json:"requirements,optional"`
	SalaryRangeMin   int      `json:"salaryRangeMin,optional"`
	SalaryRangeMax   int      `json:"salaryRangeMax,optional"`
	IsManagement     int      `json:"isManagement,optional"`
	MaxEmployees     int      `json:"maxEmployees,optional"`
	RoleIds          []string `json:"roleIds,optional"` // 角色ID列表，创建职位时同时绑定角色
}

type CreateRoleRequest struct {
	CompanyId   string `json:"companyId"`
	RoleName    string `json:"roleName"`
	RoleCode    string `json:"roleCode"`
	Description string `json:"description,optional"`
	Permissions string `json:"permissions,optional"`
}

type CreateTaskDetailComment struct {
	EmployeeId       string   `json:"employeeId"`            // 员工ID
	Comment          string   `json:"comment"`               // 评论内容
	TaskId           string   `json:"taskId"`                // 任务ID
	TaskNodeID       string   `json:"taskNodeId"`            // 任务节点ID
	UserID           string   `json:"userId"`                // 用户ID
	TaskDetailFileId string   `json:"taskDetailFileId"`      // 任务节点的详情上传的文件ID
	FileID           []string `json:"fileId,optional"`       // 返回响应的文件id
	AtEmployeeId     []string `json:"atEmployeeId,optional"` // @的员工userid，用于消息通知
}

type CreateTaskNodeRequest struct {
	TaskID        string   `json:"taskId"`                  // 总任务id
	NodeName      string   `json:"nodeName"`                // 节点名字
	NodeDetail    string   `json:"nodeDetail"`              // 该节点的详情
	NodePriority  int64    `json:"nodeType"`                // 该节点的优先级
	DepartmentID  string   `json:"departmentId"`            // 该节点的所属部门
	LeaderID      string   `json:"leaderId"`                // 该任务节点的负责人
	ExecutorIDs   []string `json:"executorIds,optional"`    // 执行者们的id
	EstimatedDays int64    `json:"estimatedHours,optional"` // 预期完成时间（小时）
	NodeStartTime string   `json:"nodeStartTime,optional"`  // 节点开始时间
	NodeDeadline  string   `json:"nodeDeadline,optional"`   // 节点截止时间
}

type CreateTaskRequest struct {
	CompanyID              string   `json:"companyId"`
	TaskTitle              string   `json:"taskTitle"`
	TaskDetail             string   `json:"taskDetail"`
	TaskPriority           int      `json:"taskPriority"`
	TaskType               int      `json:"taskType"`
	ResponsibleEmployeeIDs []string `json:"responsibleEmployeeIds,optional"`
	NodeEmployeeIDs        []string `json:"nodeEmployeeIds,optional"`
	DepartmentIDs          []string `json:"departmentIds,optional"`
	TaskDeadline           string   `json:"taskDeadline"`
	AttachmentURL          []string `json:"attachmentUrl,optional"`
}

type DeleteCompanyRequest struct {
	CompanyID string `json:"companyId"`
}

type DeleteDepartmentRequest struct {
	ID string `json:"id"`
}

type DeleteEmployeeRequest struct {
	EmployeeID string `json:"employeeId"`
}

type DeletePositionRequest struct {
	PositionID string `json:"positionId"`
}

type DeleteRoleRequest struct {
	Id string `json:"id"`
}

type DeleteTaskNodeRequest struct {
	TaskNodeID string `json:"taskNodeId"`
}

type DeleteTaskRequest struct {
	TaskID       string `json:"taskId"`
	DeleteReason string `json:"deleteReason,optional"`
}

type DepartmentInfo struct {
	ID             string `json:"id"`
	CompanyID      string `json:"companyId"`
	DepartmentName string `json:"departmentName"`
	ParentID       string `json:"parentId"`
	DepartmentCode string `json:"departmentCode"`
	ManagerID      string `json:"managerId"`
	Description    string `json:"description"`
	Status         int    `json:"status"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type DepartmentListRequest struct {
	PageReq
	CompanyID string `json:"companyId"`
	Name      string `json:"name,optional"`
}

type DispatchTaskRequest struct {
	TaskNodeID string `json:"taskNodeId"`
	EmployeeID string `json:"employeeId,optional"` // 如果为空则自动派发
}

type EmployeeInfo struct {
	ID           string `json:"id"`
	UserID       string `json:"userId"`
	CompanyID    string `json:"companyId"`
	DepartmentID string `json:"departmentId"`
	PositionID   string `json:"positionId"`
	EmployeeID   string `json:"employeeId"`
	RealName     string `json:"realName"`
	WorkEmail    string `json:"workEmail"`
	WorkPhone    string `json:"workPhone"`
	Skills       string `json:"skills"`
	RoleTags     string `json:"roleTags"`
	HireDate     string `json:"hireDate"`
	LeaveDate    string `json:"leaveDate"`
	Status       int    `json:"status"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type EmployeeLeaveRequest struct {
	EmployeeID  string `json:"employeeId"`
	LeaveReason string `json:"leaveReason"`
	LeaveDate   string `json:"leaveDate,optional"`
}

type EmployeeListRequest struct {
	PageReq
	CompanyID    string `json:"companyId"`
	DepartmentID string `json:"departmentId,optional"`
	PositionID   string `json:"positionId,optional"`
	Name         string `json:"name,optional"`
}

type EmployeeRolesRequest struct {
	EmployeeId string `json:"employeeId"` // 查询员工通过职位获得的角色
}

type GetCompanyRequest struct {
	CompanyID string `json:"companyId"`
}

type GetDepartmentRequest struct {
	ID string `json:"id"`
}

type GetEmployeeRequest struct {
	EmployeeID string `json:"employeeId"`
}

type GetHandoverRequest struct {
	HandoverID string `json:"handoverId"`
}

type GetNotificationRequest struct {
	NotificationID string `json:"notificationId"`
}

type GetPositionRequest struct {
	PositionID string `json:"positionId"`
}

type GetTaskNodeRequest struct {
	TaskNodeID string `json:"taskNodeId"`
}

type GetTaskRequest struct {
	TaskID string `json:"taskId"`
}

type HandoverInfo struct {
	HandoverID     string `json:"handoverId"`
	TaskID         string `json:"taskId"`
	FromEmployeeID string `json:"fromEmployeeId"`
	ToEmployeeID   string `json:"toEmployeeId"`
	HandoverReason string `json:"handoverReason"`
	HandoverNote   string `json:"handoverNote"`
	HandoverStatus int    `json:"handoverStatus"`
	ApproverID     string `json:"approverId"`
	Approved       int    `json:"approved"`
	ApprovalNote   string `json:"approvalNote"`
	HandoverTime   string `json:"handoverTime"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type HandoverListRequest struct {
	PageReq
	TaskID         string `json:"taskId,optional"`
	FromEmployeeID string `json:"fromEmployeeId,optional"`
	ToEmployeeID   string `json:"toEmployeeId,optional"`
	Status         int    `json:"status,optional"`
}

type HandoverTaskRequest struct {
	TaskNodeID   string `json:"taskNodeId"`
	ToEmployeeID string `json:"toEmployeeId,optional"`
	Reason       string `json:"reason"`
	Description  string `json:"description"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token            string `json:"token"`
	UserID           string `json:"userId"`
	Username         string `json:"username"`
	RealName         string `json:"realName"`
	HasJoinedCompany bool   `json:"hasJoinedCompany"`
}

type MarkNotificationReadRequest struct {
	NotificationID string `json:"notificationId"`
}

type MyTasksRequest struct {
	PageReq
	Status int `json:"status,optional"`
}

type NotificationInfo struct {
	ID          string `json:"id"`
	EmployeeID  string `json:"employeeId"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Type        int    `json:"type"`
	Priority    int    `json:"priority"`
	IsRead      int    `json:"isRead"`
	SenderID    string `json:"senderId"`
	RelatedID   string `json:"relatedId"`
	RelatedType string `json:"relatedType"`
	ReadTime    string `json:"readTime"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type NotificationListRequest struct {
	PageReq
	EmployeeID string `json:"employeeId,optional"`
	Category   int    `json:"category,optional"`
	IsRead     int    `json:"isRead,optional"`
}

type PageReq struct {
	Page     int `json:"page,optional"`
	PageSize int `json:"pageSize,optional"`
}

type PageResp struct {
	Total int         `json:"total"`
	List  interface{} `json:"list"`
}

type PositionInfo struct {
	ID               string `json:"id"`
	DepartmentID     string `json:"departmentId"`
	PositionName     string `json:"positionName"`
	PositionCode     string `json:"positionCode"`
	PositionLevel    int    `json:"positionLevel"`
	RequiredSkills   string `json:"requiredSkills"`
	JobDescription   string `json:"jobDescription"`
	Responsibilities string `json:"responsibilities"`
	Requirements     string `json:"requirements"`
	SalaryRangeMin   int    `json:"salaryRangeMin"`
	SalaryRangeMax   int    `json:"salaryRangeMax"`
	IsManagement     int    `json:"isManagement"`
	MaxEmployees     int    `json:"maxEmployees"`
	CurrentEmployees int    `json:"currentEmployees"`
	Status           int    `json:"status"`
	CreateTime       string `json:"createTime"`
	UpdateTime       string `json:"updateTime"`
}

type PositionListRequest struct {
	PageReq
	DepartmentID string `json:"departmentId,optional"`
	Name         string `json:"name,optional"`
}

type PositionRolesRequest struct {
	PositionId string `json:"positionId"` // 查询职位关联的角色
}

type RegisterRequest struct {
	Username         string `json:"username"`
	Password         string `json:"password"`
	Email            string `json:"email"`
	Phone            string `json:"phone,optional"`
	RealName         string `json:"realName"`
	VerificationCode string `json:"verificationCode,optional"` // 邮箱验证码
}

type RevokeRoleRequest struct {
	PositionId string `json:"positionId"` // 职位ID（改为从职位撤销角色）
	RoleId     string `json:"roleId"`
}

type RoleInfo struct {
	Id          string `json:"id"`
	CompanyId   string `json:"companyId"`
	RoleName    string `json:"roleName"`
	RoleCode    string `json:"roleCode"`
	Description string `json:"description"`
	Permissions string `json:"permissions"`
	Status      int    `json:"status"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type RoleListRequest struct {
	PageReq
	CompanyId string `json:"companyId,optional"`
	Keyword   string `json:"keyword,optional"`
}

type TaskDetailInfo struct {
	TaskInfo
	Logs []TaskLogInfo `json:"logs,optional"`
}

type TaskDetailRequest struct {
	TaskID string `json:"taskId"`
}

type TaskInfo struct {
	ID              string         `json:"id"`
	TaskTitle       string         `json:"taskTitle"`
	TaskDescription string         `json:"taskDescription"`
	TaskType        string         `json:"taskType"`
	Priority        int            `json:"priority"`
	Status          int            `json:"status"`
	CompanyID       string         `json:"companyId"`
	DepartmentID    string         `json:"departmentId"`
	CreatorID       string         `json:"creatorId"`
	StartTime       string         `json:"startTime"`
	Deadline        string         `json:"deadline"`
	EstimatedHours  int            `json:"estimatedHours"`
	ActualHours     int            `json:"actualHours"`
	Progress        int            `json:"progress"`
	CreateTime      string         `json:"createTime"`
	UpdateTime      string         `json:"updateTime"`
	Nodes           []TaskNodeInfo `json:"nodes,optional"`
}

type TaskListRequest struct {
	PageReq
	Keyword      string `json:"keyword,optional"`
	Status       int    `json:"status,optional"`
	CompanyID    string `json:"companyId,optional"`
	DepartmentID string `json:"departmentId,optional"`
	Priority     int    `json:"priority,optional"`
	TaskType     string `json:"taskType,optional"`
}

type TaskListResponse struct {
	List     []TaskInfo `json:"list"`
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"pageSize"`
}

type TaskLogInfo struct {
	ID         string `json:"id"`
	TaskID     string `json:"taskId"`
	TaskNodeID string `json:"taskNodeId"`
	LogType    string `json:"logType"`
	LogContent string `json:"logContent"`
	OperatorID string `json:"operatorId"`
	CreateTime string `json:"createTime"`
}

type TaskNodeInfo struct {
	ID                string `json:"id"`
	TaskID            string `json:"taskId"`
	NodeName          string `json:"nodeName"`
	NodeDetail        string `json:"nodeDetail"`
	NodeType          string `json:"nodeType"`
	Status            int    `json:"status"`
	DepartmentID      string `json:"departmentId"`
	LeaderID          string `json:"leaderId"`
	ExecutorID        string `json:"executorId"`
	NodeDeadline      string `json:"nodeDeadline"`
	EstimatedHours    int    `json:"estimatedHours"`
	ActualHours       int    `json:"actualHours"`
	Progress          int    `json:"progress"`
	PrerequisiteNodes string `json:"prerequisiteNodes"`
	CreateTime        string `json:"createTime"`
	UpdateTime        string `json:"updateTime"`
}

type TaskNodeListRequest struct {
	PageReq
	TaskID       string `json:"taskId"`
	DepartmentID string `json:"departmentId,optional"`
	Status       int    `json:"status,optional"`
}

type UpdateCompanyRequest struct {
	ID                string `json:"id"`
	Name              string `json:"name,optional"`
	CompanyAttributes int    `json:"companyAttributes,optional"`
	CompanyBusiness   int    `json:"companyBusiness,optional"`
	Description       string `json:"description,optional"`
	Address           string `json:"address,optional"`
	Phone             string `json:"phone,optional"`
	Email             string `json:"email,optional"`
}

type UpdateDepartmentRequest struct {
	ID             string `json:"id"`
	DepartmentName string `json:"departmentName,optional"`
	ParentID       string `json:"parentId,optional"`
	DepartmentCode string `json:"departmentCode,optional"`
	ManagerID      string `json:"managerId,optional"`
	Description    string `json:"description,optional"`
}

type UpdateEmployeeRequest struct {
	ID           string `json:"id"`
	DepartmentID string `json:"departmentId,optional"`
	PositionID   string `json:"positionId,optional"`
	EmployeeID   string `json:"employeeId,optional"`
	RealName     string `json:"realName,optional"`
	WorkEmail    string `json:"workEmail,optional"`
	WorkPhone    string `json:"workPhone,optional"`
	Skills       string `json:"skills,optional"`
	RoleTags     string `json:"roleTags,optional"`
	HireDate     string `json:"hireDate,optional"`
	LeaveDate    string `json:"leaveDate,optional"`
}

type UpdateInfoRequest struct {
	UserId   string             `json:"userId,optional"`   // 用户id
	NickName string             `json:"nickname,optional"` // 昵称
	Avatar   UploadInfoResponse `json:"avatar,optional"`   // 头像URL
	Bio      string             `json:"bio,optional"`      // 个人简介
	Address  string             `json:"address,optional"`  // 地址
}

type UpdatePositionRequest struct {
	ID               string `json:"id"`
	PositionName     string `json:"positionName,optional"`
	PositionCode     string `json:"positionCode,optional"`
	PositionLevel    int    `json:"positionLevel,optional"`
	RequiredSkills   string `json:"requiredSkills,optional"`
	JobDescription   string `json:"jobDescription,optional"`
	Responsibilities string `json:"responsibilities,optional"`
	Requirements     string `json:"requirements,optional"`
	SalaryRangeMin   int    `json:"salaryRangeMin,optional"`
	SalaryRangeMax   int    `json:"salaryRangeMax,optional"`
	IsManagement     int    `json:"isManagement,optional"`
	MaxEmployees     int    `json:"maxEmployees,optional"`
}

type UpdatePrerequisiteNodesRequest struct {
	NodeID            string `json:"nodeId"`            // 任务节点ID
	PrerequisiteNodes string `json:"prerequisiteNodes"` // 前置节点ID列表，逗号分隔，支持"start"
}

type UpdateRoleRequest struct {
	Id          string `json:"id"`
	RoleName    string `json:"roleName,optional"`
	RoleCode    string `json:"roleCode,optional"`
	Description string `json:"description,optional"`
	Permissions string `json:"permissions,optional"`
	Status      int    `json:"status,optional"`
}

type UpdateTaskDetailRequest struct {
	TaskId string               `json:"taskId"` // 任务对应的Id
	File   []UploadInfoResponse `json:"file"`   // 返回响应
}

type UpdateTaskNodeRequest struct {
	NodeID            string   `json:"nodeId"`
	NodeName          string   `json:"nodeName,optional"`          // 任务名称
	NodeDetail        string   `json:"nodeDetail,optional"`        // 任务节点详情
	ExecutorID        []string `json:"executorIds,optional"`       // 执行人id
	LastExecutorID    []string `json:"lastExecutorId,optional"`    // 上一位执行人的id 如果这个不为空即为更换，为空则为新增
	LeaderID          string   `json:"leaderId,optional"`          // 更换节点状态人的状态
	NodeStatus        []int    `json:"nodeStatus,optional"`        // 节点状态
	NodeDeadline      string   `json:"nodeDeadline,optional"`      // 节点截至时间
	NodeFinishTime    string   `json:"nodeFinishTime,optional"`    // 节点完成时间
	PrerequisiteNodes string   `json:"prerequisiteNodes,optional"` // 前置条件
	Progress          []int    `json:"progress,optional"`          //任务节点进度
}

type UpdateTaskProgressRequest struct {
	TaskNodeID   string `json:"taskNodeId"`
	Progress     int    `json:"progress"`
	ActualHours  int    `json:"actualHours,optional"`
	ProgressNote string `json:"progressNote,optional"`
}

type UpdateTaskRequest struct {
	TaskID          string `json:"taskId"`
	TaskTitle       string `json:"taskTitle,optional"`
	TaskDescription string `json:"taskDescription,optional"`
	Deadline        string `json:"deadline,optional"`
	Status          int    `json:"status,optional"`
	UpdateNote      string `json:"updateNote,optional"`
}

type UploadInfoRequest struct {
	Module      string `form:"module"`               // 所属业务模块：task/employee/company/department/position/handover/notification/user等
	FileType    string `form:"fileType,optional"`    // 文件类型：image/pdf/markdown/document/excel/word等（如果前端不传，后端可从文件扩展名推断）
	Category    string `form:"category,optional"`    // 文件分类：avatar/document/attachment/cover/icon等
	RelatedID   string `form:"relatedId,optional"`   // 关联的业务ID（如任务ID、用户ID、公司ID等）
	TaskNodeID  string `form:"taskNodeId,optional"`  // 关联的任务节点ID（任务附件必填）
	Description string `form:"description,optional"` // 文件描述或备注
	Tags        string `form:"tags,optional"`        // 文件标签，多个标签用逗号分隔
}

type UploadInfoResponse struct {
	RelatedID string `json:"relatedId,optional"` // 根据对应id进行存储
	FileID    string `json:"fileId"`             // 文件存储ID
	FileURL   string `json:"fileUrl"`            // 文件访问URL
	FileName  string `json:"fileName"`           // 存储后的文件名
	FileSize  int64  `json:"fileSize"`           // 文件大小
	FileType  string `json:"fileType"`           // 文件类型
}

// 任务清单相关类型
type CreateChecklistRequest struct {
	TaskNodeID string `json:"taskNodeId"`         // 任务节点ID
	Content    string `json:"content"`            // 清单内容
	SortOrder  int64  `json:"sortOrder,optional"` // 排序顺序
}

type UpdateChecklistRequest struct {
	ChecklistID string `json:"checklistId"`          // 清单ID
	Content     string `json:"content,optional"`     // 清单内容
	IsCompleted int64  `json:"isCompleted,optional"` // 是否已完成：0-未完成，1-已完成
	SortOrder   int64  `json:"sortOrder,optional"`   // 排序顺序
}

type DeleteChecklistRequest struct {
	ChecklistID string `json:"checklistId"` // 清单ID
}

type GetChecklistRequest struct {
	ChecklistID string `json:"checklistId"` // 清单ID
}

type GetChecklistListRequest struct {
	PageReq
	TaskNodeID string `json:"taskNodeId"` // 任务节点ID
}

type BatchCompleteChecklistRequest struct {
	ChecklistIDs []string `json:"checklistIds"` // 清单ID列表
	IsCompleted  int64    `json:"isCompleted"`  // 是否已完成：0-未完成，1-已完成
}

type ChecklistInfo struct {
	ID           string `json:"id"`
	TaskNodeID   string `json:"taskNodeId"`
	CreatorID    string `json:"creatorId"`
	CreatorName  string `json:"creatorName,optional"`
	Content      string `json:"content"`
	IsCompleted  int64  `json:"isCompleted"`
	CompleteTime string `json:"completeTime,optional"`
	SortOrder    int64  `json:"sortOrder"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type ChecklistStats struct {
	TaskNodeID     string `json:"taskNodeId"`
	TotalCount     int64  `json:"totalCount"`
	CompletedCount int64  `json:"completedCount"`
	Progress       int64  `json:"progress"` // 百分比进度 0-100
}

// 获取我的清单请求
type GetMyChecklistRequest struct {
	PageReq
	IsCompleted int64 `json:"isCompleted,optional"` // 筛选完成状态：-1或不传-全部，0-未完成，1-已完成
}

// 我的清单项（包含任务和节点信息）
type MyChecklistItem struct {
	ID           string `json:"id"`
	TaskNodeID   string `json:"taskNodeId"`
	TaskNodeName string `json:"taskNodeName"`
	TaskID       string `json:"taskId"`
	TaskTitle    string `json:"taskTitle"`
	Content      string `json:"content"`
	IsCompleted  int64  `json:"isCompleted"`
	CompleteTime string `json:"completeTime,optional"`
	SortOrder    int64  `json:"sortOrder"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

// ============== 附件管理相关类型 ==============

// 获取任务附件列表请求
type GetTaskAttachmentsRequest struct {
	TaskID string `json:"taskId"`
}

// 获取任务节点附件列表请求
type GetTaskNodeAttachmentsRequest struct {
	TaskNodeID string `json:"taskNodeId"`
}

// 获取文件详情请求
type GetFileDetailRequest struct {
	FileID string `json:"fileId"`
}

// 删除附件请求
type DeleteAttachmentRequest struct {
	FileID string `json:"fileId"`
}

// 附件信息
type AttachmentInfo struct {
	FileID      string `json:"fileId"`
	FileName    string `json:"fileName"`
	FileURL     string `json:"fileUrl"`
	FileType    string `json:"fileType"`
	FileSize    int64  `json:"fileSize"`
	Module      string `json:"module"`
	Category    string `json:"category"`
	RelatedID   string `json:"relatedId"`
	TaskNodeID  string `json:"taskNodeId"` // 关联的任务节点ID
	UploaderID  string `json:"uploaderId"` // 上传者ID
	Description string `json:"description"`
	Tags        string `json:"tags"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

// ============== 任务评论相关类型(MongoDB) ==============

// 创建任务评论请求
type CreateTaskCommentRequest struct {
	TaskID        string   `json:"taskId"`                 // 任务ID
	TaskNodeID    string   `json:"taskNodeId,optional"`    // 任务节点ID(可选)
	Content       string   `json:"content"`                // 评论内容
	ContentHTML   string   `json:"contentHtml,optional"`   // HTML格式内容
	AtEmployeeIDs []string `json:"atEmployeeIds,optional"` // @的员工ID列表
	ParentID      string   `json:"parentId,optional"`      // 父评论ID(回复时使用)
	AttachmentIDs []string `json:"attachmentIds,optional"` // 附件ID列表
}

// 更新任务评论请求
type UpdateTaskCommentRequest struct {
	CommentID   string `json:"commentId"`            // 评论ID
	Content     string `json:"content,optional"`     // 评论内容
	ContentHTML string `json:"contentHtml,optional"` // HTML格式内容
}

// 删除任务评论请求
type DeleteTaskCommentRequest struct {
	CommentID string `json:"commentId"`
}

// 获取任务评论列表请求
type GetTaskCommentsRequest struct {
	PageReq
	TaskID     string `json:"taskId,optional"`     // 任务ID
	TaskNodeID string `json:"taskNodeId,optional"` // 任务节点ID
}

// 点赞/取消点赞评论请求
type LikeCommentRequest struct {
	CommentID string `json:"commentId"`
	IsLike    bool   `json:"isLike"` // true为点赞，false为取消点赞
}

// 任务评论信息
type TaskCommentInfo struct {
	ID              string            `json:"id"`
	CommentID       string            `json:"commentId"`
	TaskID          string            `json:"taskId"`
	TaskNodeID      string            `json:"taskNodeId"`
	UserID          string            `json:"userId"`
	EmployeeID      string            `json:"employeeId"`
	EmployeeName    string            `json:"employeeName"`
	Content         string            `json:"content"`
	ContentHTML     string            `json:"contentHtml"`
	AtEmployeeIDs   []string          `json:"atEmployeeIds"`
	AtEmployeeNames []string          `json:"atEmployeeNames"`
	ParentID        string            `json:"parentId"`
	ReplyToUserID   string            `json:"replyToUserId"`
	ReplyToName     string            `json:"replyToName"`
	AttachmentIDs   []string          `json:"attachmentIds"`
	AttachmentURLs  []string          `json:"attachmentUrls"`
	LikeCount       int64             `json:"likeCount"`
	IsLiked         bool              `json:"isLiked"`          // 当前用户是否已点赞
	Replies         []TaskCommentInfo `json:"replies,optional"` // 回复列表
	CreateTime      string            `json:"createTime"`
	UpdateTime      string            `json:"updateTime"`
}

// ============== 附件评论标注相关类型(MongoDB) ==============

// 创建附件评论请求
type CreateAttachmentCommentRequest struct {
	FileID         string             `json:"fileId"`                  // 附件文件ID
	TaskID         string             `json:"taskId,optional"`         // 关联任务ID
	TaskNodeID     string             `json:"taskNodeId,optional"`     // 关联任务节点ID
	Content        string             `json:"content"`                 // 评论内容
	AtEmployeeIDs  []string           `json:"atEmployeeIds,optional"`  // @的员工ID列表
	AnnotationType string             `json:"annotationType,optional"` // 标注类型: point/rect/highlight/arrow
	AnnotationData *AnnotationDataReq `json:"annotationData,optional"` // 标注数据
	PageNumber     int                `json:"pageNumber,optional"`     // PDF页码
	ParentID       string             `json:"parentId,optional"`       // 父评论ID
}

// 标注数据请求
type AnnotationDataReq struct {
	X      float64 `json:"x,optional"`
	Y      float64 `json:"y,optional"`
	Width  float64 `json:"width,optional"`
	Height float64 `json:"height,optional"`
	Color  string  `json:"color,optional"`
	Text   string  `json:"text,optional"`
	StartX float64 `json:"startX,optional"`
	StartY float64 `json:"startY,optional"`
	EndX   float64 `json:"endX,optional"`
	EndY   float64 `json:"endY,optional"`
}

// 获取附件评论列表请求
type GetAttachmentCommentsRequest struct {
	PageReq
	FileID string `json:"fileId"`
}

// 标记附件评论已解决请求
type ResolveAttachmentCommentRequest struct {
	CommentID string `json:"commentId"`
}

// 删除附件评论请求
type DeleteAttachmentCommentRequest struct {
	CommentID string `json:"commentId"`
}

// 附件评论信息
type AttachmentCommentInfo struct {
	ID              string                  `json:"id"`
	CommentID       string                  `json:"commentId"`
	FileID          string                  `json:"fileId"`
	TaskID          string                  `json:"taskId"`
	TaskNodeID      string                  `json:"taskNodeId"`
	UserID          string                  `json:"userId"`
	EmployeeID      string                  `json:"employeeId"`
	EmployeeName    string                  `json:"employeeName"`
	Content         string                  `json:"content"`
	AtEmployeeIDs   []string                `json:"atEmployeeIds"`
	AtEmployeeNames []string                `json:"atEmployeeNames"`
	AnnotationType  string                  `json:"annotationType"`
	AnnotationData  *AnnotationDataReq      `json:"annotationData"`
	PageNumber      int                     `json:"pageNumber"`
	ParentID        string                  `json:"parentId"`
	ReplyToUserID   string                  `json:"replyToUserId"`
	ReplyToName     string                  `json:"replyToName"`
	IsResolved      bool                    `json:"isResolved"`
	ResolvedBy      string                  `json:"resolvedBy"`
	ResolvedAt      string                  `json:"resolvedAt"`
	Replies         []AttachmentCommentInfo `json:"replies,optional"`
	CreateTime      string                  `json:"createTime"`
	UpdateTime      string                  `json:"updateTime"`
}

// ============== 头像上传相关类型 ==============

// 上传头像请求(通过form-data传递)
type UploadAvatarRequest struct {
	UserID string `form:"userId,optional"` // 用户ID，为空则使用当前登录用户
}

// 上传头像响应
type UploadAvatarResponse struct {
	AvatarURL string `json:"avatarUrl"`
	FileID    string `json:"fileId"`
}

// ============== 验证码相关类型 ==============

// 发送验证码请求
type SendVerificationCodeRequest struct {
	Email string `json:"email"` // 邮箱地址
	Type  string `json:"type"`  // 验证码类型：register（注册）、reset_password（重置密码）
}

// 重置密码请求
type ResetPasswordRequest struct {
	Email            string `json:"email"`            // 邮箱地址
	VerificationCode string `json:"verificationCode"` // 验证码
	NewPassword      string `json:"newPassword"`      // 新密码
}

// 注册请求（带验证码）
type RegisterWithCodeRequest struct {
	Username         string `json:"username"`
	Password         string `json:"password"`
	Email            string `json:"email"`
	RealName         string `json:"realName"`
	VerificationCode string `json:"verificationCode"` // 邮箱验证码
}
