// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package company

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	departmentFieldNames          = builder.RawFieldNames(&Department{})
	departmentRows                = strings.Join(departmentFieldNames, ",")
	departmentRowsExpectAutoSet   = strings.Join(stringx.Remove(departmentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	departmentRowsWithPlaceHolder = strings.Join(stringx.Remove(departmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	departmentModel interface {
		Insert(ctx context.Context, data *Department) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Department, error)
		Update(ctx context.Context, data *Department) error
		Delete(ctx context.Context, id string) error
	}

	defaultDepartmentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Department struct {
		Id                 string         `db:"id"`                  // 部门id
		CompanyId          string         `db:"company_id"`          // 公司id
		ParentId           sql.NullString `db:"parent_id"`           // 父部门id
		DepartmentName     string         `db:"department_name"`     // 部门名
		DepartmentCode     sql.NullString `db:"department_code"`     // 部门编码
		DepartmentPriority int64          `db:"department_priority"` // 部门优先级 0--6 根据拥有者进行权限的分配，后续分配任务或者修改权限根据这个优先级来 6权限最大
		ManagerId          sql.NullString `db:"manager_id"`          // 部门经理id
		Description        sql.NullString `db:"description"`         // 部门描述
		Status             int64          `db:"status"`              // 状态 0-禁用 1-正常
		CreateTime         time.Time      `db:"create_time"`         // 创建时间
		UpdateTime         time.Time      `db:"update_time"`         // 更新时间
		DeleteTime         sql.NullTime   `db:"delete_time"`         // 删除时间
	}
)

func newDepartmentModel(conn sqlx.SqlConn) *defaultDepartmentModel {
	return &defaultDepartmentModel{
		conn:  conn,
		table: "`department`",
	}
}

func (m *defaultDepartmentModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDepartmentModel) FindOne(ctx context.Context, id string) (*Department, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", departmentRows, m.table)
	var resp Department
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDepartmentModel) Insert(ctx context.Context, data *Department) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, departmentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.CompanyId, data.ParentId, data.DepartmentName, data.DepartmentCode, data.DepartmentPriority, data.ManagerId, data.Description, data.Status, data.DeleteTime)
	return ret, err
}

func (m *defaultDepartmentModel) Update(ctx context.Context, data *Department) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, departmentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CompanyId, data.ParentId, data.DepartmentName, data.DepartmentCode, data.DepartmentPriority, data.ManagerId, data.Description, data.Status, data.DeleteTime, data.Id)
	return err
}

func (m *defaultDepartmentModel) tableName() string {
	return m.table
}
