// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package role

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	positionRoleFieldNames          = builder.RawFieldNames(&PositionRole{})
	positionRoleRows                = strings.Join(positionRoleFieldNames, ",")
	positionRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(positionRoleFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	positionRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(positionRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	positionRoleModel interface {
		Insert(ctx context.Context, data *PositionRole) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*PositionRole, error)
		FindOneByPositionIdRoleId(ctx context.Context, positionId string, roleId string) (*PositionRole, error)
		Update(ctx context.Context, data *PositionRole) error
		Delete(ctx context.Context, id string) error
	}

	defaultPositionRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PositionRole struct {
		Id         string         `db:"id"`          // 关联id
		PositionId string         `db:"position_id"` // 职位id
		RoleId     string         `db:"role_id"`     // 角色id
		GrantBy    sql.NullString `db:"grant_by"`    // 授权人id
		GrantTime  time.Time      `db:"grant_time"`  // 授权时间
		ExpireTime sql.NullTime   `db:"expire_time"` // 过期时间
		Status     int64          `db:"status"`      // 状态 0-禁用 1-正常
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
	}
)

func newPositionRoleModel(conn sqlx.SqlConn) *defaultPositionRoleModel {
	return &defaultPositionRoleModel{
		conn:  conn,
		table: "`position_role`",
	}
}

func (m *defaultPositionRoleModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPositionRoleModel) FindOne(ctx context.Context, id string) (*PositionRole, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", positionRoleRows, m.table)
	var resp PositionRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPositionRoleModel) FindOneByPositionIdRoleId(ctx context.Context, positionId string, roleId string) (*PositionRole, error) {
	query := fmt.Sprintf("select %s from %s where `position_id` = ? and `role_id` = ? limit 1", positionRoleRows, m.table)
	var resp PositionRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, positionId, roleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPositionRoleModel) Insert(ctx context.Context, data *PositionRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, positionRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.PositionId, data.RoleId, data.GrantBy, data.GrantTime, data.ExpireTime, data.Status)
	return ret, err
}

func (m *defaultPositionRoleModel) Update(ctx context.Context, newData *PositionRole) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, positionRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PositionId, newData.RoleId, newData.GrantBy, newData.GrantTime, newData.ExpireTime, newData.Status, newData.Id)
	return err
}

func (m *defaultPositionRoleModel) tableName() string {
	return m.table
}
