// Code generated by goctl. DO NOT EDIT.

package admin

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminFieldNames          = builder.RawFieldNames(&Admin{})
	adminRows                = strings.Join(adminFieldNames, ",")
	adminRowsExpectAutoSet   = strings.Join(stringx.Remove(adminFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminRowsWithPlaceHolder = strings.Join(stringx.Remove(adminFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminModel interface {
		Insert(ctx context.Context, data *Admin) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Admin, error)
		FindOneByUsername(ctx context.Context, username string) (*Admin, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*Admin, error)
		Update(ctx context.Context, data *Admin) error
		Delete(ctx context.Context, id string) error
	}

	defaultAdminModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Admin struct {
		Id            string         `db:"id"`              // 管理员ID
		Username      string         `db:"username"`        // 用户名
		PasswordHash  string         `db:"password_hash"`   // 密码哈希
		RealName      sql.NullString `db:"real_name"`       // 真实姓名
		Email         sql.NullString `db:"email"`           // 邮箱
		Phone         sql.NullString `db:"phone"`           // 手机号
		Avatar        sql.NullString `db:"avatar"`          // 头像URL
		Role          string         `db:"role"`            // 角色: super_admin/admin
		Status        int64          `db:"status"`          // 状态: 0-禁用 1-正常
		LastLoginTime sql.NullTime   `db:"last_login_time"` // 最后登录时间
		LastLoginIp   sql.NullString `db:"last_login_ip"`   // 最后登录IP
		CreateTime    time.Time      `db:"create_time"`     // 创建时间
		UpdateTime    time.Time      `db:"update_time"`     // 更新时间
		DeleteTime    sql.NullTime   `db:"delete_time"`     // 删除时间
	}
)

func newAdminModel(conn sqlx.SqlConn) *defaultAdminModel {
	return &defaultAdminModel{
		conn:  conn,
		table: "`admin`",
	}
}

func (m *defaultAdminModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminModel) FindOne(ctx context.Context, id string) (*Admin, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRows, m.table)
	var resp Admin
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByUsername(ctx context.Context, username string) (*Admin, error) {
	var resp Admin
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*Admin, error) {
	var resp Admin
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", adminRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminModel) Insert(ctx context.Context, data *Admin) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, adminRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.PasswordHash, data.RealName, data.Email, data.Phone, data.Avatar, data.Role, data.Status, data.LastLoginTime, data.LastLoginIp, data.DeleteTime)
	return ret, err
}

func (m *defaultAdminModel) Update(ctx context.Context, newData *Admin) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.PasswordHash, newData.RealName, newData.Email, newData.Phone, newData.Avatar, newData.Role, newData.Status, newData.LastLoginTime, newData.LastLoginIp, newData.DeleteTime, newData.Id)
	return err
}

func (m *defaultAdminModel) tableName() string {
	return m.table
}
