// Code generated by goctl. DO NOT EDIT.

package admin

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loginRecordFieldNames          = builder.RawFieldNames(&LoginRecord{})
	loginRecordRows                = strings.Join(loginRecordFieldNames, ",")
	loginRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(loginRecordFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(loginRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	loginRecordModel interface {
		Insert(ctx context.Context, data *LoginRecord) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*LoginRecord, error)
		Update(ctx context.Context, data *LoginRecord) error
		Delete(ctx context.Context, id string) error
	}

	defaultLoginRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LoginRecord struct {
		Id          string         `db:"id"`           // 记录ID
		UserId      string         `db:"user_id"`      // 用户ID
		UserType    string         `db:"user_type"`    // 用户类型: user/admin
		Username    sql.NullString `db:"username"`     // 用户名
		LoginTime   time.Time      `db:"login_time"`   // 登录时间
		LoginIp     sql.NullString `db:"login_ip"`     // 登录IP
		UserAgent   sql.NullString `db:"user_agent"`   // 浏览器UA
		LoginStatus int64          `db:"login_status"` // 登录状态: 0-失败 1-成功
		FailReason  sql.NullString `db:"fail_reason"`  // 失败原因
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
	}
)

func newLoginRecordModel(conn sqlx.SqlConn) *defaultLoginRecordModel {
	return &defaultLoginRecordModel{
		conn:  conn,
		table: "`login_record`",
	}
}

func (m *defaultLoginRecordModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLoginRecordModel) FindOne(ctx context.Context, id string) (*LoginRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginRecordRows, m.table)
	var resp LoginRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginRecordModel) Insert(ctx context.Context, data *LoginRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, loginRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.UserType, data.Username, data.LoginTime, data.LoginIp, data.UserAgent, data.LoginStatus, data.FailReason)
	return ret, err
}

func (m *defaultLoginRecordModel) Update(ctx context.Context, newData *LoginRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.UserType, newData.Username, newData.LoginTime, newData.LoginIp, newData.UserAgent, newData.LoginStatus, newData.FailReason, newData.Id)
	return err
}

func (m *defaultLoginRecordModel) tableName() string {
	return m.table
}
